### ISSUE TITLE
I get a couple of compile errors when updated MailKitLite from 4.3.0 to 4.4.0

### ISSUE THREAD

**Issue by DierkDroth** [jstedfast/MailKit#1721]
@jstedfast any idea what's going on?

6>C:\Users\dierk\Documents\unusual-src\Unusual.Common\Mail\MailClient.cs(100,31,100,53): error CS0012: The type 'FormatOptions' is defined in an assembly that is not referenced. You must add a reference to assembly 'MimeKitLite, Version=4.4.0.0, Culture=neutral, PublicKeyToken=bede1c8a46c66814'.
6>C:\Users\dierk\Documents\unusual-src\Unusual.Common\Mail\MailClient.cs(628,19,628,41): error CS0012: The type 'HeaderId' is defined in an assembly that is not referenced. You must add a reference to assembly 'MimeKitLite, Version=4.4.0.0, Culture=neutral, PublicKeyToken=bede1c8a46c66814'.
6>C:\Users\dierk\Documents\unusual-src\Unusual.Common\Mail\MailClient.cs(629,19,629,41): error CS0012: The type 'HeaderId' is defined in an assembly that is not referenced. You must add a reference to assembly 'MimeKitLite, Version=4.4.0.0, Culture=neutral, PublicKeyToken=bede1c8a46c66814'.
6>C:\Users\dierk\Documents\unusual-src\Unusual.Common\Mail\MailClient.cs(641,29,641,56): error CS0012: The type 'MimeMessage' is defined in an assembly that is not referenced. You must add a reference to assembly 'MimeKitLite, Version=4.4.0.0, Culture=neutral, PublicKeyToken=bede1c8a46c66814'.
6>C:\Users\dierk\Documents\unusual-src\Unusual.Common\Mail\MailClient.cs(686,72,686,94): error CS0012: The type 'HeaderId' is defined in an assembly that is not referenced. You must add a reference to assembly 'MimeKitLite, Version=4.4.0.0, Culture=neutral, PublicKeyToken=bede1c8a46c66814'.
6>C:\Users\dierk\Documents\unusual-src\Unusual.Common\Mail\MailClient.cs(1336,8,1336,34): error CS0012: The type 'MimeMessage' is defined in an assembly that is not referenced. You must add a reference to assembly 'MimeKitLite, Version=4.4.0.0, Culture=neutral, PublicKeyToken=bede1c8a46c66814'.
6>C:\Users\dierk\Documents\unusual-src\Unusual.Common\Mail\MailClient.cs(1862,52,1862,74): error CS0012: The type 'HeaderId' is defined in an assembly that is not referenced. You must add a reference to assembly 'MimeKitLite, Version=4.4.0.0, Culture=neutral, PublicKeyToken=bede1c8a46c66814'.

**Comment by jstedfast** [comment]
Fixed with 4.4.0.1

**Comment by DierkDroth** [comment]
Thanks for taking care @jstedfast
