### ISSUE TITLE
Failed to update to latest MailKit 4.1.0

### ISSUE THREAD

**Issue by DierkDroth** [jstedfast/MailKit#1596]
After update from 4.0.0. to 4.1.0 my solution no longer compiles and I get this error
```
1>------ Rebuild All started: Project: Unusual.Common, Configuration: Debug Any CPU ------
Restored C:\Users\dierk\Documents\unusual-src\Unusual.Wasm\Unusual.Wasm.csproj (in 126 ms).
1>CSC : error CS1705: Assembly 'MailKitLite' with identity 'MailKitLite, Version=4.1.0.0, Culture=neutral, PublicKeyToken=4e064fe7c44a8f1b' uses 'MimeKitLite, Version=4.1.0.0, Culture=neutral, PublicKeyToken=bede1c8a46c66814' which has a higher version than referenced assembly 'MimeKitLite' with identity 'MimeKitLite, Version=4.0.0.0, Culture=neutral, PublicKeyToken=bede1c8a46c66814'
1>Done building project "Unusual.Common.csproj" -- FAILED.
```

Rebuild/clean all didn't help

@jstedfast would you have any idea what's going on?

**Comment by jstedfast** [comment]
Sounds like somehow the MimeKitLite package included a MimeKitLite 4.0.0 assembly (or maybe the assembly version attribute wasn't updated correctly).

**Comment by DierkDroth** [comment]
@jstedfast sorry, I'm not sure I follow. Is there something I needed to do to clear up the issue?

**Comment by jstedfast** [comment]
What I meant was that the MimeKitLite 4.1.0 package contains assemblies that had the version 4.0.0.0 instead of 4.1.0.0.

I just released 4.1.0.1 - you can either update MimeKitLite to 4.1.0.1 or you can update MailKitLite to 4.1.0.1 which depends on MimeKit 4.1.0.1.

Either way will work. Neither package contains any fixes other than the version fix.

**Comment by DierkDroth** [comment]
Thanks @jstedfast. That fixed the issue
